### PR TITLE
fix the issue that new files created via wwctl overlay edit have permission 755 && removing lines during wwctl overlay edit didn't work

### LINKED ISSUE #1235: removing lines during wwctl overlay edit didn't work
### Steps to reproduce

> I'm having an issue with wwctl overlay edit, if I add lines it works ok, but removing lines didn't work. Is there any way to remove lines properly with the overlay edit command?

> and the most weird if I delete a line that is not the last of the file it duplicates the last one, but if I also edit the last one it adds the previous last one

### Error message

_No response_

### Information on your system

[not provided]

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### LINKED ISSUE #1236: new files created with wwctl overlay edit have 755 permissions
### Steps to reproduce

New files created with wwctl overlay edit have 755 permissions while before they were created with 644.

### Error message

new files created with wwctl overlay edit have 755 permissions while before they were created with 644

### Information on your system

[none provided]

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

It looks like this PR can fix two issues at the same time. (issue #1235 and issue #1236)
By directly doing `os.Rename` from temp file created each time for the edit to the targeted overlay file, we can solve the both issues at the same time. 

## This fixes or addresses the following GitHub issues:

 - Fixes #1235 
 - Fixes #1236 

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

## Test
https://github.com/warewulf/warewulf/assets/2051711/bbad7ebc-1a6e-40bb-a167-2b64b1c3ceb5

### CODE REVIEW

**Comment by anderbubble** [comment]
Rebased to main.

File: internal/app/wwctl/overlay/edit/main.go [hunk 1]
```diff
@@ -122,16 +115,14 @@ func CobraRunE(cmd *cobra.Command, args []string) error {
 		}
 	}
 
-	destination, destinationErr := os.OpenFile(overlayFile, os.O_RDWR|os.O_CREATE, os.FileMode(PermMode))
-	if destinationErr != nil {
-		wwlog.Error("Unable to update %s: %s", overlayFile, destinationErr)
+	err := os.Chmod(tempFile.Name(), os.FileMode(0644))
```
Comment (anderbubble) [inline internal/app/wwctl/overlay/edit/main.go:118]: I think this PR looks good in general (with my testing so far, anyway) but I don't think this chmod is necessary; when I used this PR with the chmod removed, I got a file with 0600, which I think is even better (and I don't like the 0644 being hardcoded).

```
-rw-------. 1 root root       0 Jul  2 16:58 testfile
-rw-------. 1 root root     669 Jul  2 16:59 testfile.ww
```

Let me know what you think, though.

**Review by anderbubble — CHANGES_REQUESTED** [review]

File: internal/app/wwctl/overlay/edit/main.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/app/wwctl/overlay/edit/main.go]: thanks for that! reflected in this commit
https://github.com/warewulf/warewulf/pull/1238/commits/b61dd17dbcec7d1c37d791318a7f1a14512b53ef

**Review by mslacken — APPROVED** [review]

**Comment by anderbubble** [comment]
Squashed and added some detail to the commit messages.

**Review by anderbubble — APPROVED** [review]
