### PR TITLE
`wwctl node set` requires mandatory pattern input

### LINKED ISSUE #502: `wwctl node set` wants to modify nodes even though no other arguments
Observed behavior:

```
[I am root!@frankie:(bare)::~]# wwctl node set 

*** WARNING: This command will modify all nodes! ***

? Are you sure you want to modify 55 nodes(s)? [y/N] █
```

Expected behavior:

An error or usage message.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

`wwctl node set` requires mandatory pattern input

## This fixes or addresses the following GitHub issues:

- Fixes #502

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/app/wwctl/node/set/root.go [hunk 1]
```diff
@@ -31,11 +31,11 @@ func GetCommand() *cobra.Command {
 	vars.nodeConf = node.NewConf()
 	baseCmd := &cobra.Command{
 		DisableFlagsInUseLine: true,
-		Use:                   "set [OPTIONS] PATTERN [PATTERN ...]",
+		Use:                   "set [OPTIONS] PATTERN",
 		Short:                 "Configure node properties",
 		Long:                  "This command sets configuration properties for nodes matching PATTERN.\n\nNote: use the string 'UNSET' to remove a configuration",
 		Aliases:               []string{"modify"},
-		Args:                  cobra.MinimumNArgs(0),
+		Args:                  cobra.ExactArgs(1), // require pattern as a mandatory arg
```
Comment (anderbubble) [inline internal/app/wwctl/node/set/root.go:38]: @JasonYangShadow Would `MinimumNAgrs(1)` work, too? That way we could still supply multiple nodes as multiple "patterns."

Comment (JasonYangShadow) [reply internal/app/wwctl/node/set/root.go]: thanks! updated. `MinimumNArgs` should work better in this case.

**Comment by mslacken** [comment]
@JasonYangShadow Can you please rebase?

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow Can you please rebase?

thanks! rebased
