### PR TITLE
Dracut boot refinement

### LINKED ISSUE #1261: dracut not working with secure mode
### Steps to reproduce

Using a container that includes a dracut initramfs, built with:

    dracut --force --no-hostonly --add wwinit --kver $(ls /lib/modules | head -n1)

and a node that was configured for dracut, with:

    wwctl node set $node --tagadd GrubMenuEntry=dracut

and with "secure: true" in warewulf.conf, the node fails to boot. warewulfd.log shows:

    DENIED : Non-privileged port: $ip:55810
 
Node boots fine with secure: false.

### Error message

````
RECV   : hwaddr: XX:XX:XX:XX:XX:XX, ipaddr: A.B.C.D:55810, stage: runtime
DENIED : Non-privileged port: A.B.C.D:55810
````

### Information on your system

Commit 18b99353bec1d21dd53761e110e4ced58ad07b60
```
wwctl version:   4.5.4-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.4-1"
```

warewulf running on Rocky 8.9

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by anderbubble**
Alternative implementation for #1269. Also incorporates a fix from #1370.

The new dracut boot method bloated /proc/cmdline, and exposed asset-tag and uuid to unprivileged users. This PR moves the parsing of dracut URIs from iPXE to the dracut script pase-wwinit.sh, using dmidecode to obtain asset-tag and uuid, leaving only the IP and port of the warewulf server in /proc/cmdline.

Additionally, it forces runtime overlays to be pulled from a static local port (986) to allow dracut boot to be used with secure mode. Port 986 is used instead of 987 to prevent a race condition of the system releasing the port before wwclient starts and tries to bind to 987.

Lastly, add the required curl, cpio and now dmidecode packages to warewulf.spec for warewulf-dracut subpackage

## This fixes or addresses the following GitHub issues:

 - Fixes #1261 

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
@JasonYangShadow could you review this?

File: dracut/modules.d/90wwinit/parse-wwinit.sh [hunk 1]
```diff
@@ -6,10 +6,14 @@
 if [ "${root}" = "wwinit" ]
 then
     info "root=${root}"
-    export wwinit_container=$(getarg wwinit.container=); info "wwinit.container=${wwinit_container}"
-    export wwinit_system=$(getarg wwinit.system=); info "wwinit.system=${wwinit_system}"
-    export wwinit_runtime=$(getarg wwinit.runtime=); info "wwinit.runtime=${wwinit_runtime}"
-    export wwinit_kmods=$(getarg wwinit.kmods=); info "wwinit.kmods=${wwinit_kmods}"
+    wwinit_uri="$(getarg wwinit.uri)"
+    export wwinit_container="${wwinit_uri}container&compress=gz"; info "winit_container=${wwinit_container}"
```
Comment (JasonYangShadow) [inline dracut/modules.d/90wwinit/parse-wwinit.sh:10]: should `info "winit_container` be `info "wwinit_container"` missing `w` in `winit` ?

**Comment by JasonYangShadow** [comment]
@anderbubble 
I tried steps listed here
https://warewulf.org/docs/main/contents/boot-management.html#booting-with-dracut

I can enable the dracut boot, but failing at the step of  `Found root=wwinit but no container image` 
chrome_9cMjGccLOV
MobaXterm_ao3YE4bo2N
chrome_19XGrSYKFb

File: dracut/modules.d/90wwinit/parse-wwinit.sh (hunk 1 above)
Comment (anderbubble) [reply dracut/modules.d/90wwinit/parse-wwinit.sh]: Thanks. Fixed.

**Comment by anderbubble** [comment]
With this not just working for @JasonYangShadow on first try, I'm going to again delay this to v4.5.7, particularly since I'm traveling and away from my homelab / test environment.

**Comment by epruesse** [comment]
Confirmed, as is this PR leads to:
`dracut: FATAL: Found root=wwinit but no container image. Cannot boot from Warewulf.`

**Comment by epruesse** [comment]
The URLs where missing `&stage=` so it was trying to pull the dracut.pxe instead, and because wwctl won't compress that, not getting anything. I put in a new PR because I couldn't patch this one.

**Comment by anderbubble** [comment]
Closing in favor of #1370.

**Comment by anderbubble** [comment]
Re-opening to further extend #1370 to not expose assetkey and uuid in /proc/cmdline.

**Comment by anderbubble** [comment]
Ok! @jeburks2 and @JasonYangShadow I'm back over here now, with another commit added to #1370 to move uuid and assetkey back into dracut + dmidecode / away from `/proc/cmdline`. (Sorry I doubted you, @jeburks2!)

Let me know what you think. If it works for you (and it worked for me; both ipxe and grub) then I'll get it merged for v4.5.7.

**Comment by jeburks2** [comment]
Works great! I tested it successfully in two environments: one with secure mode and asset keys, and one without. Both booted nodes using dracut without issues.

**Review by mslacken — APPROVED** [review]
