### PR TITLE
Fix excessive line spacing issue when listing nodes

### LINKED ISSUE #1241: node list -a output have excessive line spacing
### Steps to reproduce

If there is a line of parameters that is wrapped around into multiple lines all other lines will have empty spacing for no reason.

```
wwctl node add node01
wwctl node set -A "this is very long string that contain a lot of kernel args so they are wrapped in multiple lines on node list --all output" node01
wwctl node list node01 -a
```

### Error message

_No response_

### Information on your system

NAME=“Rocky Linux”
VERSION=“8.9 (Green Obsidian)”
ID=“rocky”
ID_LIKE=“rhel centos fedora”
VERSION_ID=“8.9”
PLATFORM_ID=“platform:el8”
PRETTY_NAME=“Rocky Linux 8.9 (Green Obsidian)”
ANSI_COLOR=“0;32”
LOGO=“fedora-logo-icon”
CPE_NAME=“cpe:/o:rocky:rocky:8:GA”
HOME_URL=“[https://rockylinux.org/ 1](https://rockylinux.org/)”
BUG_REPORT_URL=“https://bugs.rockylinux.org/”
SUPPORT_END=“2029-05-31”
ROCKY_SUPPORT_PRODUCT=“Rocky-Linux-8”
ROCKY_SUPPORT_PRODUCT_VERSION=“8.9”
REDHAT_SUPPORT_PRODUCT=“Rocky Linux”
REDHAT_SUPPORT_PRODUCT_VERSION=“8.9”

wwctl version: 4.5.2-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.2-1"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Fix excessive line spacing issue when listing nodes

## This fixes or addresses the following GitHub issues:

 - Fixes #1241

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### Before
image

### After
image

### CODE REVIEW

File: internal/app/wwctl/node/list/main.go [hunk 1]
```diff
@@ -44,6 +44,7 @@ func CobraRunE(vars *variables) func(cmd *cobra.Command, args []string) (err err
 				for _, val := range nodeInfo.Output[1:] {
 					ph.Append(strings.Split(val, ":=:"))
 				}
+				ph.SetColMinWidth(3, 10) // set the min width of last column (value column) in order to avoid of empty newlines.
```
Comment (anderbubble) [inline internal/app/wwctl/node/list/main.go:47]: Rather than changing this here, which only affects `wwctl node list`, it should be applied in `NewPrintHelper` so that it affects all of `wwctl`. It also needs to remove all trailing whitespace; this appears to have removed some, but the lines still have trailing whitespace.

I'm uncertain whether tablewriter is really the best fit for this; but the quickest thing might be to have tablewriter [render to a string](https://github.com/olekukonko/tablewriter?tab=readme-ov-file#render-table-into-a-string) and then use a regular expression to remove `(?m) *$` before printing.

**Review by anderbubble — CHANGES_REQUESTED** [review]

File: internal/app/wwctl/node/list/main.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/app/wwctl/node/list/main.go]: yeah, thanks, I've reflected the code as suggested and adjusted test cases as well.

**Review by anderbubble — APPROVED** [review]
Looks good! I made a small change to fix a possible bug type; but it's the kind of thing that would definitely be caught by your tests if I'd made a mistake, so I'm going to go ahead and merge.

Thanks!
