### PR TITLE
Fix regression in container exec argument parsing

### LINKED ISSUE #1250: argument passing causes error in container exec / shell
### Steps to reproduce

```
# wwctl container exec --bind /patches:/patches  --bind /apps:/apps  base-91  /bin/bash
ERROR  : Failed executing container command: unable to create run directory: mkdir /usr/local/warewulf/var/warewulf/chroots/--bind/run: no such file or directory
```

### Error message

```
ERROR  : Failed executing container command: unable to create run directory: mkdir /usr/local/warewulf/var/warewulf/chroots/--bind/run: no such file or directory
```

### Information on your system

v4.5.3

Rocky Linux.

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

Fix a regression in v4.5.3 which broke container exec argument parsing.

## This fixes or addresses the following GitHub issues:

- Fixes #1250

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken sorry for the regression. Frankly, it's one of those "I don't know how it ever worked before" situations; but I think the new code is clearer.

@JasonYangShadow could you review this and potentially add some tests for it as well?

**Comment by JasonYangShadow** [comment]
> @mslacken sorry for the regression. Frankly, it's one of those "I don't know how it ever worked before" situations; but I think the new code is clearer.
> 
> @JasonYangShadow could you review this and potentially add some tests for it as well?

I've checked the changes, lgtm. I will try adding some unit test cases.

**Comment by anderbubble** [comment]
Rebased to main.

**Comment by JasonYangShadow** [comment]
> @mslacken sorry for the regression. Frankly, it's one of those "I don't know how it ever worked before" situations; but I think the new code is clearer.
> 
> @JasonYangShadow could you review this and potentially add some tests for it as well?

added unit test cases in this commit
https://github.com/warewulf/warewulf/pull/1251/commits/b1d871d23d3a12feb9b7bf598a04930ca789264f
feel free to update them.

File: internal/app/wwctl/container/exec/main.go [hunk 1]
```diff
@@ -20,12 +20,25 @@ import (
...
+		Cloneflags: syscall.CLONE_NEWUTS | syscall.CLONE_NEWPID | syscall.CLONE_NEWNS,
+	}
+	child.Stdin = cmd.InOrStdin()
+	child.Stdout = cmd.OutOrStdout()
+	child.Stderr = cmd.ErrOrStderr()
+	return child.Run()
+}
+
+var childCommandFunc = runChildCmd
+
```
Comment (mslacken) [inline internal/app/wwctl/container/exec/main.go:35]: For what do we need this variable?

Comment (anderbubble) [reply internal/app/wwctl/container/exec/main.go:35]: It allows the command to be mocked out during testing, since the tests can't actually run `runChildCmd`.

Comment (anderbubble) [reply internal/app/wwctl/container/exec/main.go:35]: See https://github.com/warewulf/warewulf/pull/1251/files#diff-3b25d09560b836b0497ca86e6409117819d182a28a24fc7c182ed06c3006e644R29-R32

**Comment by JasonYangShadow** [comment]
It looks okay to me. @mslacken has any comments? Test cases in warewulf are still unit tests, If we have e2e tests for warewulf, it'll be great, for example for this `container exec` we should test with real image. We might need a test framework for achieving this purpose. Such as https://onsi.github.io/ginkgo/#top

**Review by JasonYangShadow — APPROVED** [review]
