### PR TITLE
fix the failure when updating overlay files existing on different par…

### LINKED ISSUE #1312: Unable to update overlay file
### Steps to reproduce

I am trying to edit an overlay file:

`wwctl overaly edit generic /etc/fstab.ww`

### Error message

`ERROR  : Unable to update /var/lib/warewulf/overlays/generic/rootfs/etc/fstab.ww: rename /tmp/ww-overlay-edit-3137351506 /var/lib/warewulf/overlays/generic/rootfs/etc/fstab.ww: invalid cross-device link`

### Information on your system

the /var/lib/warewulf and /tmp are on separate partitions

mount output for relevant mount points
`tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,seclabel)`
`/dev/sda12 on /var/lib/warewulf type xfs (rw,nosuid,nodev,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)`

[root@master2 ~]# wwctl version
wwctl version:	 4.5.5-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.5-1"

[root@master2 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Fix the failure that when editing overlay files on different partitions (tmpfs and /var are on different partitions). 

## This fixes or addresses the following GitHub issues:

 - Fixes #1312

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

## Test

1. Before patch
Screenshot 2024-07-25 140318

2. After patch
Screenshot 2024-07-25 140721

### CODE REVIEW

File: internal/app/wwctl/overlay/edit/main.go [hunk 1]
```diff
@@ -115,10 +115,17 @@ func CobraRunE(cmd *cobra.Command, args []string) error {
...
 	if err != nil {
-		wwlog.Error("Unable to update %s: %s", overlayFile, err)
-		os.Exit(1)
+		// if it fails, which probably means that they exists on different partitions
+		// fallback to data copy
+		wwlog.Debug("Unable to rename temp file: %s to overlay file: %s, try copying the data", tempFile.Name(), overlayFile)
+		cerr := util.CopyFile(tempFile.Name(), overlayFile)
+		if cerr != nil {
+			wwlog.Error("Unable to copy data from temp file: %s to target file: %s, err: %s", tempFile.Name(), overlayFile, err)
+			os.Exit(1)
```
Comment (mslacken) [inline internal/app/wwctl/overlay/edit/main.go:127]: Why not return the error here? `os.Exit(1)` is always not nice.
Also we should remove the `tempFile` afterwards.

**Review by mslacken — CHANGES_REQUESTED** [review]
* remove the tempfile
* avoid `os.Exit()`

File: internal/app/wwctl/overlay/edit/main.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/app/wwctl/overlay/edit/main.go]: thanks for the comment!
I saw that previous code is using `os.Exit`, anyway, I've changed to `return error` in this case.
tempfile is removed here
https://github.com/warewulf/warewulf/blob/b61e3918908bd48ee7bb30af659fe946cc06efac/internal/app/wwctl/overlay/edit/main.go#L69C2-L69C8

**Comment by mslacken** [comment]
@JasonYangShadow Can you also add this fix to profile edit?

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow Can you also add this fix to profile edit?

yeah, sure, let me create another PR for `profile edit`

**Review by mslacken — APPROVED** [review]
